# Generated by Django 6.0.4 on 2026-05-09 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="division_id",
        ),
        migrations.RemoveField(
            model_name="subjects",
            name="division_id",
        ),
        migrations.RemoveField(
            model_name="year",
            name="course_id",
        ),
        migrations.RemoveField(
            model_name="subjects",
            name="year_id",
        ),
        migrations.RemoveField(
            model_name="students",
            name="year_id",
        ),
        migrations.AlterField(
            model_name="adminhod",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="attendancereport",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="courses",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="feedbackstaffs",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="feedbackstudent",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="leavereportstaff",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="leavereportstudent",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notificationstaffs",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notificationstudent",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="staffs",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="studentresult",
            name="updated_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="students",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="subjects",
            name="staff_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="subjects",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name="Division",
        ),
        migrations.DeleteModel(
            name="Year",
        ),
    ]
