# Generated by Django 6.0.4 on 2026-05-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0002_remove_students_division_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("file", models.FileField(upload_to="notices/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
