# Generated by Django 6.0.4 on 2026-05-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0004_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentresult",
            name="practical_marks",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="studentresult",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="studentresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="SyllabusCoverage",
        ),
    ]
