# Generated by Django 6.0.4 on 2026-05-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0005_studentresult_practical_marks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentresult",
            name="assignment_marks",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentresult",
            name="ct1_marks",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentresult",
            name="ct2_marks",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentresult",
            name="endsem_marks",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentresult",
            name="midsem_marks",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentresult",
            name="practical_marks",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
