# Generated by Django 6.0.4 on 2026-05-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_management_app",
            "0006_alter_studentresult_assignment_marks_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="division",
            field=models.CharField(
                choices=[("A", "A Division"), ("B", "B Division")],
                default="A",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="roll_no",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="students",
            name="year",
            field=models.CharField(
                choices=[
                    ("FY", "First Year"),
                    ("SY", "Second Year"),
                    ("TY", "Third Year"),
                    ("Final", "Final Year"),
                ],
                default="FY",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
