# Generated by Django 6.0.4 on 2026-05-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_management_app",
            "0007_students_division_students_roll_no_students_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="roll_no",
            field=models.CharField(default="", max_length=20, unique=True),
        ),
    ]
