# Generated by Django 6.0.4 on 2026-05-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0008_alter_students_roll_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="roll_no",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
