# Generated by Django 6.0.4 on 2026-05-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0011_alter_students_roll_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="roll_no",
            field=models.CharField(default="UNKNOWN", max_length=20, unique=True),
        ),
    ]
